# Numpy tutorial

In [1]:
import numpy as np

In [2]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
a.shape

(3, 4)

In [4]:
a.size

12

In [5]:
a.ndim

2

In [6]:
# N-dimensional arrays

In [10]:
a = np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [12]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((2,3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [15]:
np.empty((2,3))

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])